## View ( Reshape과 동일)

In [3]:
import numpy as np
import torch

t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]])

ft = torch.FloatTensor(t)
print(ft)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [5]:
print(ft.shape)

torch.Size([2, 2, 3])


In [13]:
# 3차원을 2차원으로도 가능
print(ft.view([-1,3])) # 12 개를 맞추는 행은 알아서 지정
print(ft.view([-1,6]))
print(ft.view(12))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


## Squeeze (dimension이 1인경우 날려)

In [15]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [18]:
print(ft.squeeze())


ft = ft.squeeze(dim=1)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze ( 원하는 dimension에 1 넣어줌, 대신 무조건 dim argument 필요함)

In [26]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [28]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [30]:
print(ft.view(-1,1))

tensor([[0.],
        [1.],
        [2.]])


## Type Casting

In [31]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [33]:
ft = lt.float()
print(ft)

tensor([1., 2., 3., 4.])


In [35]:
bt = lt.bool()
print(bt)

tensor([True, True, True, True])


In [39]:
bt = torch.ByteTensor([True,True,False,True])
print(bt)

print(bt.long())

tensor([1, 1, 0, 1], dtype=torch.uint8)
tensor([1, 1, 0, 1])


In [42]:
bt = torch.BoolTensor([True,True,False,True])
print(bt)

print(bt.long())
print(bt.float())

tensor([ True,  True, False,  True])
tensor([1, 1, 0, 1])
tensor([1., 1., 0., 1.])


## Concatenate (이어붙이기)

In [46]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[6,7]])

print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [6., 7.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 6., 7.]])


## Stacking (cat의 응용)

In [47]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [50]:
print(torch.stack([x,y,z])) # 쌓기
print(torch.stack([x,y,z], dim=1)) # 쌓인 부분의 행 -> 열 변경

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [51]:
# 같은 경우
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [54]:
x = torch.FloatTensor([[0,1,2],[3,4,5]])
print(x.shape)
print(x)

torch.Size([2, 3])
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [56]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [58]:
print(torch.ones(2,2))
print(torch.zeros(3,3))

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation (_ 언더스코어 이용)

In [63]:
x = torch.FloatTensor([[1,2],[3,4],[5,6]])
print(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [64]:
print(x.mul(2))
print(x)

tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [65]:
print(x.mul_(2))
print(x)

tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])
tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])


In [69]:
x = x.view(2,3)
print(x)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
