In [1]:
import numpy as np
import torch

## Numpy Practice

In [3]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print(t.ndim)
print(t.shape)

1
(7,)


In [5]:
print(t[2:])

[2. 3. 4. 5. 6.]


In [6]:
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
print(t.ndim)
print(t.shape)

2
(4, 3)


## PyTorch Practice

In [14]:
t = torch.IntTensor([0,1,2,3,4,5,6])
print(t)

tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int32)


In [16]:
print(t.shape)
print(t.dim())
print(t.size())

torch.Size([7])
1
torch.Size([7])


In [21]:
print(t[0])
print(t[:2])
print(t[0], t[3], t[2])
print(t[:-1])

tensor(0, dtype=torch.int32)
tensor([0, 1], dtype=torch.int32)
tensor(0, dtype=torch.int32) tensor(3, dtype=torch.int32) tensor(2, dtype=torch.int32)
tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)


In [22]:
t = torch.IntTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [25]:
print(t.shape)
print(t.size())
print(t.dim())

torch.Size([4, 3])
torch.Size([4, 3])
2


In [31]:
print(t[0])
print(t[1,2])
print(t[:, 0])
print(t[:, :-1])

tensor([1, 2, 3], dtype=torch.int32)
tensor(6, dtype=torch.int32)
tensor([ 1,  4,  7, 10], dtype=torch.int32)
tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]], dtype=torch.int32)


## Broadcasting

In [32]:
# Same shape vector
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [33]:
# Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [35]:
# 2x1 Vector + 1x2 Vector
m1 = torch.FloatTensor([[1,2]]) # 1x2
m2 = torch.FloatTensor([[1],[3]]) # 2x1
print(m1 + m2)

tensor([[2., 3.],
        [4., 5.]])


## Multiplication vs Matrix Muliplication

In [38]:
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2x2
m2 = torch.FloatTensor([[1],[2]]) # 2x1

In [39]:
# 일반 곱셈, elementwise 방식
print(m1 * m2) # 브로드캐스팅도 적용
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [42]:
# 행렬의 곱 (내적 or 외적)
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


## Mean

In [47]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [49]:
# 정수형의 자료형에서는 mean 값 불가능
t = torch.IntTensor([1,2])
print(t.mean())

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Int

In [54]:
t = torch.FloatTensor([[1,2],[3,4]])

print(t.mean(dim=0)) # 열 평균
print(t.mean(dim=1)) # 행 평균
print(t.mean(dim=-1)) # 각 차원별 마지막 차원 평균

print(t.mean()) # 전체 평균

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
tensor(2.5000)


## Sum

In [57]:
t = torch.FloatTensor([[1,2],[3,4]])

print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

print(t.sum())

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])
tensor(10.)


## Max와 Argmax

In [62]:
t = torch.FloatTensor([[1,2],[3,4]])

print(t.max()) # 그냥 max값만 리턴해줌

print(t.max(dim=0)) # 해당 범위의 max값과, 인덱스를 리턴해줌(여기서는 dim=0이므로 열 인덱스)

print(t.max(dim=1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
