In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [ ]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [ ]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [ ]:
# 파이토치의 exp 함수
print(torch.exp(torch.FloatTensor([1])))

tensor([2.7183])


In [ ]:
w = torch.zeros([2,1], requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
# hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(w) + b)))
hypothesis = torch.sigmoid(x_train.matmul(w) + b)

In [ ]:
# 손실함수 직접 구하기
losses = -((y_train * torch.log(hypothesis)) + ((1-y_train) * torch.log(1-hypothesis)))
cost = losses.mean()

print(losses)
print(cost)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)
tensor(0.6931, grad_fn=<MeanBackward0>)


In [ ]:
# 내장 이진분류 손실함수 가져오기
cost = F.binary_cross_entropy(hypothesis, y_train)
print(cost)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)


In [ ]:
# 전체 모델
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

w = torch.zeros([2,1], requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w,b], lr=1)

epochs = 1000
for epoch in range(1, epochs+1):
    hypothesis = torch.sigmoid(x_train.matmul(w) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('반복: {:.4f}, Cost: {:.4f}'.format(epoch, cost.item()))

반복: 100.0000, Cost: 0.1356
반복: 200.0000, Cost: 0.0810
반복: 300.0000, Cost: 0.0581
반복: 400.0000, Cost: 0.0454
반복: 500.0000, Cost: 0.0373
반복: 600.0000, Cost: 0.0317
반복: 700.0000, Cost: 0.0276
반복: 800.0000, Cost: 0.0244
반복: 900.0000, Cost: 0.0219
반복: 1000.0000, Cost: 0.0199


In [ ]:
print(w)
print(b)

tensor([[3.2521],
        [1.5174]], requires_grad=True)
tensor([-14.4777], requires_grad=True)


In [39]:
test_result = torch.sigmoid(x_train.matmul(w) + b)
print(test_result)

tensor([[2.7711e-04],
        [3.1636e-02],
        [3.9014e-02],
        [9.5618e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)


In [40]:
prediction = test_result >= torch.FloatTensor([0.5])
print(prediction.byte())

tensor([[0],
        [0],
        [0],
        [1],
        [1],
        [1]], dtype=torch.uint8)


In [41]:
accuracy = prediction.float() == y_train
print(accuracy)

tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])
